DROP TABLE if EXISTS POST CASCADE;

CREATE TABLE POST (
    POST_ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    TITLE VARCHAR(100) NOT NULL COMMENT '제목',
    CONTENT VARCHAR(3000) NOT NULL COMMENT '내용',
    WRITER VARCHAR(20) NOT NULL COMMENT '작성자',
    VIEW_CNT int(10) NOT NULL COMMENT '조회수',
    NOTICE_YN TINYINT(1) NOT NULL COMMENT '공지글 여부',
    DELETE_YN TINYINT(1) NOT NULL COMMENT '삭제 여부',
    CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '생성일 시',
    MODIFIED_DATE DATETIME DEFAULT NULL COMMENT '최종 수정일 시',
    PRIMARY KEY (POST_ID)
) COMMENT '게시글';